# Generated by Django 5.2 on 2025-04-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='filme',
            name='duracao',
            field=models.DurationField(blank=True, help_text='Duration in HH:MM:SS format', null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(default='', max_length=255),
        ),
    ]
