# Generated by Django 5.2 on 2025-04-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filme_diretor_filme_duracao_filme_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='genero',
            new_name='generos',
        ),
    ]
